// 60+ additional FMCG products to seed alongside the curated ones in seed.ts.
// Images use picsum.photos (deterministic per slug — always returns a valid placeholder).
// Admin can later swap to Cloudinary uploads via /admin/products edit page.

type ExtraProduct = {
  name: string;
  slug: string;
  description: string;
  categorySlug: string;
  brandSlug: string;
  originCountries: string[];
  packaging?: Record<string, string | number>;
  shelfLifeMin?: number;
  shelfLifeMax?: number;
  moqHint?: string;
  availability?: string;
  featured?: boolean;
  specs?: Record<string, string>;
};

export function placeholderImage(slug: string): string {
  return `https://picsum.photos/seed/${slug}/640/480`;
}

export const EXTRA_PRODUCTS: ExtraProduct[] = [
  // ── DAIRY (10) ──────────────────────────────────────────────────
  { name: "Pinar Full-Cream UHT Milk 1L", slug: "pinar-uht-milk-1l", description: "UHT-treated full-cream milk in Tetra Pak, 12-month shelf life. Premium Turkish dairy.", categorySlug: "dairy", brandSlug: "pinar", originCountries: ["Turkey"], packaging: { caseSize: "12x1L" }, moqHint: "1 pallet (45 cases)", featured: true, specs: { Volume: "1 L", Packaging: "Tetra Pak", "Shelf Life": "12 months" }, shelfLifeMin: 360, shelfLifeMax: 365 },
  { name: "SEK Strained Yogurt 1kg", slug: "sek-strained-yogurt-1kg", description: "Thick Turkish strained (Süzme) yogurt. Refrigerated transport required.", categorySlug: "dairy", brandSlug: "sek", originCountries: ["Turkey"], packaging: { caseSize: "6x1kg" }, moqHint: "Reefer container only", availability: "on_request", specs: { Weight: "1 kg", "Storage": "2–8 °C" } },
  { name: "Pinar Beyaz Peynir 500g", slug: "pinar-feta-500g", description: "Traditional Turkish white cheese (beyaz peynir) in brine, vacuum sealed.", categorySlug: "dairy", brandSlug: "pinar", originCountries: ["Turkey"], packaging: { caseSize: "12x500g" }, moqHint: "1 pallet", specs: { Weight: "500 g", "Fat content": "45%", Type: "Brined" } },
  { name: "Pinar Kashar Cheese 500g", slug: "pinar-kashar-500g", description: "Aged Turkish kashar cheese block, vacuum sealed. Suitable for export.", categorySlug: "dairy", brandSlug: "pinar", originCountries: ["Turkey"], packaging: { caseSize: "12x500g" }, moqHint: "1 pallet", specs: { Weight: "500 g", Aging: "60 days" } },
  { name: "SEK Butter 250g", slug: "sek-butter-250g", description: "Turkish unsalted butter, 82% fat content. Vacuum wrapped.", categorySlug: "dairy", brandSlug: "sek", originCountries: ["Turkey"], packaging: { caseSize: "24x250g" }, moqHint: "1 pallet (40 cases)", specs: { Weight: "250 g", "Fat content": "82%", Type: "Unsalted" } },
  { name: "Pinar Labne Cheese 200g", slug: "pinar-labne-200g", description: "Creamy Levantine-style labne, ideal for Middle Eastern markets.", categorySlug: "dairy", brandSlug: "pinar", originCountries: ["Turkey"], packaging: { caseSize: "24x200g" }, moqHint: "1 pallet", specs: { Weight: "200 g", Style: "Levantine" } },
  { name: "SEK Ayran 200ml", slug: "sek-ayran-200ml", description: "Traditional yogurt drink. 24x200ml multi-packs.", categorySlug: "dairy", brandSlug: "sek", originCountries: ["Turkey"], packaging: { caseSize: "24x200ml" }, moqHint: "1 pallet (60 cases)", specs: { Volume: "200 ml" } },
  { name: "Pinar Cream Cheese 200g", slug: "pinar-cream-cheese-200g", description: "Spreadable cream cheese tub. Refrigerated.", categorySlug: "dairy", brandSlug: "pinar", originCountries: ["Turkey"], packaging: { caseSize: "12x200g" }, moqHint: "1 pallet", availability: "on_request", specs: { Weight: "200 g" } },
  { name: "Pinar Mozzarella 200g", slug: "pinar-mozzarella-200g", description: "Fresh mozzarella balls in brine pouch.", categorySlug: "dairy", brandSlug: "pinar", originCountries: ["Turkey"], packaging: { caseSize: "12x200g" }, moqHint: "Reefer required", specs: { Weight: "200 g", Storage: "2–8 °C" } },
  { name: "SEK Sour Cream 200g", slug: "sek-sour-cream-200g", description: "Premium sour cream in plastic cup. Refrigerated.", categorySlug: "dairy", brandSlug: "sek", originCountries: ["Turkey"], packaging: { caseSize: "12x200g" }, moqHint: "Reefer required", specs: { Weight: "200 g", "Fat content": "30%" } },

  // ── SNACKS & CONFECTIONERY (10) ─────────────────────────────────
  { name: "Ulker Albeni Bar 40g", slug: "ulker-albeni-40g", description: "Caramel + chocolate-coated wafer bar. Iconic Turkish snack.", categorySlug: "snacks-confectionery", brandSlug: "ulker", originCountries: ["Turkey"], packaging: { caseSize: "24x40g" }, moqHint: "1 pallet (60 cases)", featured: true, specs: { Weight: "40 g", Type: "Caramel wafer" } },
  { name: "Ulker Cocostar Bar 25g", slug: "ulker-cocostar-25g", description: "Coconut-filled chocolate bar.", categorySlug: "snacks-confectionery", brandSlug: "ulker", originCountries: ["Turkey"], packaging: { caseSize: "24x25g" }, moqHint: "1 pallet (60 cases)", specs: { Weight: "25 g", Filling: "Coconut" } },
  { name: "ETi Negro Sandwich Biscuit", slug: "eti-negro-100g", description: "Cocoa biscuit sandwich with cream filling. Turkish classic since 1972.", categorySlug: "snacks-confectionery", brandSlug: "eti", originCountries: ["Turkey"], packaging: { caseSize: "12x100g" }, moqHint: "1 pallet (72 cases)", featured: true, specs: { Weight: "100 g", Type: "Sandwich biscuit" } },
  { name: "ETi Burçak Cookies 184g", slug: "eti-burcak-184g", description: "Whole-grain oat cookies with a slight sweetness. Family pack.", categorySlug: "snacks-confectionery", brandSlug: "eti", originCountries: ["Turkey"], packaging: { caseSize: "12x184g" }, moqHint: "1 pallet (72 cases)", specs: { Weight: "184 g", Type: "Oat cookies" } },
  { name: "Ulker Chocofresh 35g", slug: "ulker-chocofresh-35g", description: "Cocoa cake with chocolate cream filling. Individually wrapped.", categorySlug: "snacks-confectionery", brandSlug: "ulker", originCountries: ["Turkey"], packaging: { caseSize: "24x35g" }, moqHint: "1 pallet (72 cases)", specs: { Weight: "35 g", Type: "Filled cake" } },
  { name: "Ferrero Rocher 200g (16 pcs)", slug: "ferrero-rocher-200g", description: "Premium hazelnut chocolates in golden wrappers. Gift box, 16 pieces.", categorySlug: "snacks-confectionery", brandSlug: "ferrero", originCountries: ["Turkey", "Italy"], packaging: { caseSize: "6x200g" }, moqHint: "1 pallet", featured: true, specs: { Weight: "200 g", Pieces: "16" } },
  { name: "Kinder Surprise Egg 20g", slug: "kinder-surprise-20g", description: "Milk chocolate egg with toy surprise inside. Suitable for retail and gifting.", categorySlug: "snacks-confectionery", brandSlug: "ferrero", originCountries: ["Turkey"], packaging: { caseSize: "72x20g" }, moqHint: "1 pallet (60 cases)", specs: { Weight: "20 g", Type: "Chocolate + toy" } },
  { name: "ETi Cin Strawberry Biscuit", slug: "eti-cin-strawberry-100g", description: "Cocoa biscuit sandwich with strawberry cream. Strong volume seller.", categorySlug: "snacks-confectionery", brandSlug: "eti", originCountries: ["Turkey"], packaging: { caseSize: "12x100g" }, moqHint: "1 pallet (72 cases)", specs: { Weight: "100 g" } },
  { name: "Ulker Caramio Bar 32g", slug: "ulker-caramio-32g", description: "Soft caramel filled chocolate bar.", categorySlug: "snacks-confectionery", brandSlug: "ulker", originCountries: ["Turkey"], packaging: { caseSize: "24x32g" }, moqHint: "1 pallet (72 cases)", specs: { Weight: "32 g" } },
  { name: "ETi Cici Bebe Biscuit 172g", slug: "eti-cici-bebe-172g", description: "Iron-fortified biscuit, popular among children. Family pack.", categorySlug: "snacks-confectionery", brandSlug: "eti", originCountries: ["Turkey"], packaging: { caseSize: "10x172g" }, moqHint: "1 pallet (72 cases)", specs: { Weight: "172 g", Fortification: "Iron + vitamins" } },

  // ── BEVERAGES (10) ──────────────────────────────────────────────
  { name: "Hayat Su Natural Mineral Water 500ml", slug: "hayat-water-500ml", description: "Premium Turkish spring water. Crystal-clear, low sodium.", categorySlug: "beverages", brandSlug: "hayat", originCountries: ["Turkey"], packaging: { caseSize: "24x500ml" }, moqHint: "1 pallet (84 cases)", featured: true, specs: { Volume: "500 ml", "Sodium": "Low" } },
  { name: "Hayat Su Sparkling 750ml Glass", slug: "hayat-sparkling-750ml", description: "Sparkling mineral water in elegant glass bottle for HORECA.", categorySlug: "beverages", brandSlug: "hayat", originCountries: ["Turkey"], packaging: { caseSize: "12x750ml" }, moqHint: "1 pallet", specs: { Volume: "750 ml", Style: "Sparkling", Bottle: "Glass" } },
  { name: "Tamek Apple Juice 1L Tetra", slug: "tamek-apple-1l", description: "100% pure apple juice from concentrate.", categorySlug: "beverages", brandSlug: "tamek", originCountries: ["Turkey"], packaging: { caseSize: "12x1L" }, moqHint: "1 pallet (45 cases)", specs: { Volume: "1 L", "Sugar added": "No" } },
  { name: "Tamek Cherry Juice 1L", slug: "tamek-cherry-1l", description: "Premium Turkish sour cherry juice. Popular in MENA markets.", categorySlug: "beverages", brandSlug: "tamek", originCountries: ["Turkey"], packaging: { caseSize: "12x1L" }, moqHint: "1 pallet (45 cases)", featured: true, specs: { Volume: "1 L", Type: "Sour cherry" } },
  { name: "Tamek Pomegranate Juice 1L", slug: "tamek-pomegranate-1l", description: "Pure pomegranate juice, no added sugar.", categorySlug: "beverages", brandSlug: "tamek", originCountries: ["Turkey"], packaging: { caseSize: "12x1L" }, moqHint: "1 pallet (45 cases)", specs: { Volume: "1 L" } },
  { name: "Nescafe Classic Jar 100g", slug: "nescafe-classic-100g", description: "Iconic instant coffee jar.", categorySlug: "beverages", brandSlug: "nestle", originCountries: ["Turkey"], packaging: { caseSize: "12x100g" }, moqHint: "1 pallet (60 cases)", featured: true, specs: { Weight: "100 g", Type: "Instant coffee" } },
  { name: "Nescafe Gold 200g", slug: "nescafe-gold-200g", description: "Premium freeze-dried instant coffee.", categorySlug: "beverages", brandSlug: "nestle", originCountries: ["Turkey"], packaging: { caseSize: "6x200g" }, moqHint: "1 pallet (72 cases)", specs: { Weight: "200 g", Type: "Freeze-dried" } },
  { name: "Lipton Yellow Label Tea 100 bags", slug: "lipton-yellow-100", description: "Classic black tea, 100 tea bags.", categorySlug: "beverages", brandSlug: "unilever", originCountries: ["Turkey"], packaging: { caseSize: "12x200g" }, moqHint: "1 pallet (60 cases)", specs: { Bags: "100", Weight: "200 g" } },
  { name: "Hayat Su 5L PET", slug: "hayat-water-5l", description: "5-liter family-size still mineral water.", categorySlug: "beverages", brandSlug: "hayat", originCountries: ["Turkey"], packaging: { caseSize: "4x5L" }, moqHint: "1 pallet (50 cases)", specs: { Volume: "5 L" } },
  { name: "Tamek Orange Juice 1L", slug: "tamek-orange-1l", description: "100% pure orange juice, Mediterranean origin.", categorySlug: "beverages", brandSlug: "tamek", originCountries: ["Turkey"], packaging: { caseSize: "12x1L" }, moqHint: "1 pallet (45 cases)", specs: { Volume: "1 L" } },

  // ── CLEANING (10) ───────────────────────────────────────────────
  { name: "ABC Matik Laundry Powder 9kg", slug: "abc-matik-9kg", description: "High-performance laundry detergent powder for top-loading machines.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "2x9kg" }, moqHint: "1 pallet (40 cases)", featured: true, specs: { Weight: "9 kg", Type: "Powder", "Wash cycles": "120" } },
  { name: "ABC Liquid Laundry 3L", slug: "abc-liquid-laundry-3l", description: "Concentrated liquid laundry detergent. Universal fabric.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "4x3L" }, moqHint: "1 pallet (40 cases)", specs: { Volume: "3 L", "Wash cycles": "60" } },
  { name: "ABC Dishwashing Liquid 1.5L", slug: "abc-dish-liquid-15l", description: "Lemon-scented dishwashing liquid. Cuts grease fast.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "8x1.5L" }, moqHint: "1 pallet (60 cases)", specs: { Volume: "1.5 L", Scent: "Lemon" } },
  { name: "ABC Bleach 5L", slug: "abc-bleach-5l", description: "Liquid bleach for laundry and surface cleaning.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "4x5L" }, moqHint: "1 pallet (40 cases)", specs: { Volume: "5 L" } },
  { name: "ABC Floor Cleaner 4L", slug: "abc-floor-4l", description: "All-purpose floor cleaner with anti-bacterial formula.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "4x4L" }, moqHint: "1 pallet (40 cases)", specs: { Volume: "4 L" } },
  { name: "ABC Toilet Bowl Cleaner 750ml", slug: "abc-toilet-750ml", description: "Thick gel toilet bowl cleaner with antibacterial action.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "12x750ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "750 ml" } },
  { name: "ABC Glass Cleaner 750ml", slug: "abc-glass-750ml", description: "Streak-free glass and mirror cleaner with trigger spray.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "12x750ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "750 ml" } },
  { name: "ABC Fabric Softener 4L", slug: "abc-softener-4l", description: "Long-lasting fragrance fabric softener. Concentrated.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "4x4L" }, moqHint: "1 pallet (40 cases)", specs: { Volume: "4 L" } },
  { name: "ABC Dish Tablet 60 pcs", slug: "abc-dish-tab-60", description: "All-in-one dishwasher tablets, 60 count.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "8x60ct" }, moqHint: "1 pallet (60 cases)", specs: { Tablets: "60" } },
  { name: "ABC Multi-Surface Spray 750ml", slug: "abc-multi-spray-750ml", description: "Versatile cleaning spray for kitchens and bathrooms.", categorySlug: "cleaning-products", brandSlug: "abc-deterjan", originCountries: ["Turkey"], packaging: { caseSize: "12x750ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "750 ml" } },

  // ── PERSONAL CARE (8) ───────────────────────────────────────────
  { name: "Duru Olive Oil Soap Bar 4x150g", slug: "duru-olive-soap-bar", description: "Traditional Turkish olive oil soap, multi-pack.", categorySlug: "personal-care-cosmetics", brandSlug: "duru", originCountries: ["Turkey"], packaging: { caseSize: "12x4x150g" }, moqHint: "1 pallet (60 cases)", featured: true, specs: { "Pack": "4 bars", "Type": "Olive oil" } },
  { name: "Duru Hair Shampoo 600ml", slug: "duru-shampoo-600ml", description: "Sulfate-free shampoo for daily use.", categorySlug: "personal-care-cosmetics", brandSlug: "duru", originCountries: ["Turkey"], packaging: { caseSize: "12x600ml" }, moqHint: "1 pallet (60 cases)", specs: { Volume: "600 ml" } },
  { name: "Duru Liquid Hand Soap 500ml", slug: "duru-handsoap-500ml", description: "Moisturizing liquid hand soap, pump bottle.", categorySlug: "personal-care-cosmetics", brandSlug: "duru", originCountries: ["Turkey"], packaging: { caseSize: "12x500ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "500 ml" } },
  { name: "Duru Body Wash 500ml", slug: "duru-bodywash-500ml", description: "Moisturizing body wash, multiple scent variants available.", categorySlug: "personal-care-cosmetics", brandSlug: "duru", originCountries: ["Turkey"], packaging: { caseSize: "12x500ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "500 ml" } },
  { name: "Duru Hair Conditioner 600ml", slug: "duru-conditioner-600ml", description: "Repairing hair conditioner.", categorySlug: "personal-care-cosmetics", brandSlug: "duru", originCountries: ["Turkey"], packaging: { caseSize: "12x600ml" }, moqHint: "1 pallet (60 cases)", specs: { Volume: "600 ml" } },
  { name: "Duru Roll-On Deodorant 50ml", slug: "duru-rollon-50ml", description: "48-hour protection roll-on antiperspirant.", categorySlug: "personal-care-cosmetics", brandSlug: "duru", originCountries: ["Turkey"], packaging: { caseSize: "24x50ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "50 ml" } },
  { name: "Duru Toothpaste Mint 75ml", slug: "duru-toothpaste-75ml", description: "Fluoride toothpaste, mint flavor.", categorySlug: "personal-care-cosmetics", brandSlug: "duru", originCountries: ["Turkey"], packaging: { caseSize: "24x75ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "75 ml" } },
  { name: "Duru Shaving Foam 200ml", slug: "duru-shaving-200ml", description: "Rich-lather shaving foam for sensitive skin.", categorySlug: "personal-care-cosmetics", brandSlug: "duru", originCountries: ["Turkey"], packaging: { caseSize: "12x200ml" }, moqHint: "1 pallet (60 cases)", specs: { Volume: "200 ml" } },

  // ── CANNED & JARRED (10) ────────────────────────────────────────
  { name: "Tamek Tomato Paste 830g Jar", slug: "tamek-tomato-paste-830", description: "Double concentrated tomato paste. Premium Turkish tomatoes.", categorySlug: "canned-jarred-foods", brandSlug: "tamek", originCountries: ["Turkey"], packaging: { caseSize: "12x830g" }, moqHint: "1 pallet (72 cases)", featured: true, specs: { Weight: "830 g", Concentration: "Double" } },
  { name: "Tamek Tomato Paste 4.5kg Tin", slug: "tamek-tomato-paste-45kg", description: "Catering size tomato paste, 4.5kg tin.", categorySlug: "canned-jarred-foods", brandSlug: "tamek", originCountries: ["Turkey"], packaging: { caseSize: "6x4.5kg" }, moqHint: "1 pallet (60 cases)", specs: { Weight: "4.5 kg", Format: "Tin" } },
  { name: "Marassi Green Olives 1kg", slug: "marassi-green-olives-1kg", description: "Premium green olives in brine, glass jar.", categorySlug: "canned-jarred-foods", brandSlug: "marassi", originCountries: ["Turkey", "Egypt"], packaging: { caseSize: "6x1kg" }, moqHint: "1 pallet (90 cases)", featured: true, specs: { Weight: "1 kg", Type: "Whole green" } },
  { name: "Marassi Black Olives 1kg", slug: "marassi-black-olives-1kg", description: "Naturally cured black olives, glass jar.", categorySlug: "canned-jarred-foods", brandSlug: "marassi", originCountries: ["Turkey", "Egypt"], packaging: { caseSize: "6x1kg" }, moqHint: "1 pallet (90 cases)", specs: { Weight: "1 kg", Type: "Whole black" } },
  { name: "Tamek Stuffed Vine Leaves 400g", slug: "tamek-vine-leaves-400g", description: "Pre-cooked dolma in olive oil, ready to serve.", categorySlug: "canned-jarred-foods", brandSlug: "tamek", originCountries: ["Turkey"], packaging: { caseSize: "12x400g" }, moqHint: "1 pallet (72 cases)", specs: { Weight: "400 g" } },
  { name: "Tamek Roasted Eggplant Salad 400g", slug: "tamek-eggplant-400g", description: "Roasted aubergine spread, ready to eat.", categorySlug: "canned-jarred-foods", brandSlug: "tamek", originCountries: ["Turkey"], packaging: { caseSize: "12x400g" }, moqHint: "1 pallet (72 cases)", specs: { Weight: "400 g" } },
  { name: "Marassi Chickpeas Canned 400g", slug: "marassi-chickpeas-400g", description: "Cooked chickpeas in brine, tin can.", categorySlug: "canned-jarred-foods", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "24x400g" }, moqHint: "1 pallet (90 cases)", specs: { Weight: "400 g" } },
  { name: "Marassi Red Kidney Beans 400g", slug: "marassi-kidney-beans-400g", description: "Cooked red kidney beans in tin can.", categorySlug: "canned-jarred-foods", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "24x400g" }, moqHint: "1 pallet (90 cases)", specs: { Weight: "400 g" } },
  { name: "Tamek Tahini Sesame Paste 300g", slug: "tamek-tahini-300g", description: "Pure sesame seed paste, glass jar.", categorySlug: "canned-jarred-foods", brandSlug: "tamek", originCountries: ["Turkey"], packaging: { caseSize: "12x300g" }, moqHint: "1 pallet (84 cases)", specs: { Weight: "300 g" } },
  { name: "Marassi Pickles Mixed 1kg", slug: "marassi-pickles-1kg", description: "Mixed Mediterranean pickles in brine.", categorySlug: "canned-jarred-foods", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "6x1kg" }, moqHint: "1 pallet (90 cases)", specs: { Weight: "1 kg" } },

  // ── PASTA, RICE & GRAINS (8) ────────────────────────────────────
  { name: "Torku Spaghetti 500g", slug: "torku-spaghetti-500g", description: "Premium Turkish durum wheat pasta. Bronze die cut.", categorySlug: "pasta-rice-grains", brandSlug: "torku", originCountries: ["Turkey"], packaging: { caseSize: "20x500g" }, moqHint: "1 pallet (90 cases)", featured: true, specs: { Weight: "500 g", "Wheat": "Durum" } },
  { name: "Torku Penne 500g", slug: "torku-penne-500g", description: "Classic penne shape, durum wheat semolina.", categorySlug: "pasta-rice-grains", brandSlug: "torku", originCountries: ["Turkey"], packaging: { caseSize: "20x500g" }, moqHint: "1 pallet (90 cases)", specs: { Weight: "500 g" } },
  { name: "Torku Fusilli 500g", slug: "torku-fusilli-500g", description: "Spiral pasta, ideal for thick sauces.", categorySlug: "pasta-rice-grains", brandSlug: "torku", originCountries: ["Turkey"], packaging: { caseSize: "20x500g" }, moqHint: "1 pallet (90 cases)", specs: { Weight: "500 g" } },
  { name: "Torku Basmati Rice 5kg", slug: "torku-basmati-5kg", description: "Long-grain basmati rice, premium quality. Family-size bag.", categorySlug: "pasta-rice-grains", brandSlug: "torku", originCountries: ["Turkey", "India"], packaging: { caseSize: "4x5kg" }, moqHint: "1 pallet (40 cases)", featured: true, specs: { Weight: "5 kg", Type: "Long-grain basmati" } },
  { name: "Torku Jasmine Rice 1kg", slug: "torku-jasmine-1kg", description: "Fragrant jasmine rice, Thai origin packed in Turkey.", categorySlug: "pasta-rice-grains", brandSlug: "torku", originCountries: ["Thailand"], packaging: { caseSize: "10x1kg" }, moqHint: "1 pallet (90 cases)", specs: { Weight: "1 kg", Type: "Jasmine" } },
  { name: "Torku Bulgur Coarse 1kg", slug: "torku-bulgur-coarse-1kg", description: "Coarse-cut bulgur wheat, ideal for pilaf.", categorySlug: "pasta-rice-grains", brandSlug: "torku", originCountries: ["Turkey"], packaging: { caseSize: "10x1kg" }, moqHint: "1 pallet (90 cases)", specs: { Weight: "1 kg", Cut: "Coarse" } },
  { name: "Torku Wheat Flour 5kg", slug: "torku-flour-5kg", description: "All-purpose wheat flour, premium milling.", categorySlug: "pasta-rice-grains", brandSlug: "torku", originCountries: ["Turkey"], packaging: { caseSize: "4x5kg" }, moqHint: "1 pallet (40 cases)", specs: { Weight: "5 kg" } },
  { name: "Torku Couscous 500g", slug: "torku-couscous-500g", description: "Medium-grain couscous, North African style.", categorySlug: "pasta-rice-grains", brandSlug: "torku", originCountries: ["Turkey"], packaging: { caseSize: "20x500g" }, moqHint: "1 pallet (90 cases)", specs: { Weight: "500 g" } },

  // ── OILS & CONDIMENTS (8) ───────────────────────────────────────
  { name: "Marassi Sunflower Oil 5L", slug: "marassi-sunflower-5l", description: "Refined sunflower oil for cooking and frying.", categorySlug: "oils-condiments", brandSlug: "marassi", originCountries: ["Turkey", "Ukraine"], packaging: { caseSize: "4x5L" }, moqHint: "1 pallet (40 cases)", featured: true, specs: { Volume: "5 L", Type: "Refined sunflower" } },
  { name: "Marassi Sunflower Oil 1L", slug: "marassi-sunflower-1l", description: "Retail-size refined sunflower oil bottle.", categorySlug: "oils-condiments", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x1L" }, moqHint: "1 pallet (90 cases)", specs: { Volume: "1 L" } },
  { name: "Marassi Extra Virgin Olive Oil 500ml", slug: "marassi-evoo-500ml", description: "Cold-pressed extra virgin olive oil from Aegean Turkey.", categorySlug: "oils-condiments", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x500ml" }, moqHint: "1 pallet (90 cases)", featured: true, specs: { Volume: "500 ml", Acidity: "< 0.5%", Type: "Extra virgin" } },
  { name: "Marassi Olive Oil 1L Tin", slug: "marassi-olive-1l-tin", description: "Refined olive oil in tin can. Catering size.", categorySlug: "oils-condiments", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x1L" }, moqHint: "1 pallet (90 cases)", specs: { Volume: "1 L", Container: "Tin" } },
  { name: "Marassi Ketchup 450g", slug: "marassi-ketchup-450g", description: "Premium tomato ketchup in squeeze bottle.", categorySlug: "oils-condiments", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x450g" }, moqHint: "1 pallet (84 cases)", specs: { Weight: "450 g" } },
  { name: "Marassi Mayonnaise 450g", slug: "marassi-mayo-450g", description: "Creamy mayonnaise in squeeze bottle.", categorySlug: "oils-condiments", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x450g" }, moqHint: "1 pallet (84 cases)", specs: { Weight: "450 g" } },
  { name: "Marassi Hot Pepper Sauce 350ml", slug: "marassi-hot-sauce-350ml", description: "Aegean hot pepper sauce. Medium spice level.", categorySlug: "oils-condiments", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x350ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "350 ml", Spice: "Medium" } },
  { name: "Marassi Pomegranate Sauce 350ml", slug: "marassi-pom-sauce-350ml", description: "Sweet-sour pomegranate molasses for Levantine cuisine.", categorySlug: "oils-condiments", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x350ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "350 ml" } },

  // ── BABY PRODUCTS (6) ───────────────────────────────────────────
  { name: "Marassi Baby Diapers Size 3 (50 pcs)", slug: "marassi-diaper-3", description: "Soft & dry baby diapers, size 3 (4–9 kg), 50 pieces.", categorySlug: "baby-products", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "4x50" }, moqHint: "1 pallet (60 cases)", specs: { Size: "3", "Weight range": "4–9 kg", Count: "50" } },
  { name: "Marassi Baby Diapers Size 4 (44 pcs)", slug: "marassi-diaper-4", description: "Baby diapers size 4 (7–14 kg).", categorySlug: "baby-products", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "4x44" }, moqHint: "1 pallet (60 cases)", specs: { Size: "4", "Weight range": "7–14 kg", Count: "44" } },
  { name: "Marassi Wet Wipes 64 pcs", slug: "marassi-wipes-64", description: "Soft baby wet wipes, alcohol-free, dermatologically tested.", categorySlug: "baby-products", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x64ct" }, moqHint: "1 pallet (84 cases)", featured: true, specs: { Count: "64 wipes", Feature: "Alcohol-free" } },
  { name: "Nestle Baby Cereal Wheat 250g", slug: "nestle-cereal-250g", description: "Iron-fortified wheat cereal for babies 6 months+.", categorySlug: "baby-products", brandSlug: "nestle", originCountries: ["Turkey"], packaging: { caseSize: "12x250g" }, moqHint: "1 pallet (84 cases)", specs: { Weight: "250 g", "Age": "6+ months" } },
  { name: "Nestle Baby Formula Stage 1 800g", slug: "nestle-formula-1", description: "Infant formula 0-6 months, premium quality.", categorySlug: "baby-products", brandSlug: "nestle", originCountries: ["Turkey"], packaging: { caseSize: "6x800g" }, moqHint: "1 pallet (60 cases)", availability: "on_request", specs: { Weight: "800 g", "Age": "0–6 months" } },
  { name: "Marassi Baby Shampoo 400ml", slug: "marassi-baby-shampoo-400ml", description: "Tear-free baby shampoo with chamomile.", categorySlug: "baby-products", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x400ml" }, moqHint: "1 pallet (84 cases)", specs: { Volume: "400 ml" } },

  // ── DRIED FRUITS & NUTS (6) ─────────────────────────────────────
  { name: "Marassi Roasted Hazelnuts 1kg", slug: "marassi-roasted-hazelnuts-1kg", description: "Premium roasted hazelnuts from Giresun, vacuum sealed.", categorySlug: "dried-fruits-nuts", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "10x1kg" }, moqHint: "1 pallet (60 cases)", featured: true, specs: { Weight: "1 kg", Origin: "Giresun" } },
  { name: "Marassi Dried Apricots 500g", slug: "marassi-apricots-500g", description: "Sun-dried Malatya apricots, no sulfur added.", categorySlug: "dried-fruits-nuts", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x500g" }, moqHint: "1 pallet (84 cases)", featured: true, specs: { Weight: "500 g", Origin: "Malatya", "Sulfur": "None" } },
  { name: "Marassi Pistachios Roasted 500g", slug: "marassi-pistachios-500g", description: "Roasted and salted Turkish pistachios.", categorySlug: "dried-fruits-nuts", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x500g" }, moqHint: "1 pallet (60 cases)", specs: { Weight: "500 g", Preparation: "Roasted + salted" } },
  { name: "Marassi Sultanas (Golden Raisins) 1kg", slug: "marassi-sultanas-1kg", description: "Premium Turkish sultanas from Aegean region.", categorySlug: "dried-fruits-nuts", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "10x1kg" }, moqHint: "1 pallet (60 cases)", specs: { Weight: "1 kg" } },
  { name: "Marassi Almonds Raw 1kg", slug: "marassi-almonds-1kg", description: "Premium raw almonds, vacuum sealed.", categorySlug: "dried-fruits-nuts", brandSlug: "marassi", originCountries: ["Turkey", "USA"], packaging: { caseSize: "10x1kg" }, moqHint: "1 pallet (60 cases)", specs: { Weight: "1 kg", Type: "Raw" } },
  { name: "Marassi Walnuts Halves 500g", slug: "marassi-walnuts-500g", description: "Halved walnut kernels, premium quality.", categorySlug: "dried-fruits-nuts", brandSlug: "marassi", originCountries: ["Turkey"], packaging: { caseSize: "12x500g" }, moqHint: "1 pallet (84 cases)", specs: { Weight: "500 g", Cut: "Halves" } },
];
